apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ingress-auth
    annotations:
        avp.kubernetes.io/path: "projects/zencastr-prod/secrets/weaviate_ingress-auth_{{- .Values.zenv -}}"
data:
    auth: <weaviate_ingress-auth_{{- .Values.zenv -}} | base64encode>